package Pojo;
// Generated Mar 22, 2015 7:46:58 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Course generated by hbm2java
 */
public class Course  implements java.io.Serializable {


     private Integer idCourse;
     private Group group;
     private Department department;
     private String name;
     private String description;
     private int isActive;
     private Set staffs = new HashSet(0);
     private Set labs = new HashSet(0);

    public Course() {
    }

	
    public Course(Group group, Department department, String name, String description, int isActive) {
        this.group = group;
        this.department = department;
        this.name = name;
        this.description = description;
        this.isActive = isActive;
    }
    public Course(Group group, Department department, String name, String description, int isActive, Set staffs, Set labs) {
       this.group = group;
       this.department = department;
       this.name = name;
       this.description = description;
       this.isActive = isActive;
       this.staffs = staffs;
       this.labs = labs;
    }
   
    public Integer getIdCourse() {
        return this.idCourse;
    }
    
    public void setIdCourse(Integer idCourse) {
        this.idCourse = idCourse;
    }
    public Group getGroup() {
        return this.group;
    }
    
    public void setGroup(Group group) {
        this.group = group;
    }
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public int getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(int isActive) {
        this.isActive = isActive;
    }
    public Set getStaffs() {
        return this.staffs;
    }
    
    public void setStaffs(Set staffs) {
        this.staffs = staffs;
    }
    public Set getLabs() {
        return this.labs;
    }
    
    public void setLabs(Set labs) {
        this.labs = labs;
    }




}


