package Pojo;
// Generated Mar 22, 2015 11:30:04 AM by Hibernate Tools 3.6.0



/**
 * CourseHasGroupId generated by hbm2java
 */
public class CourseHasGroupId  implements java.io.Serializable {


     private int courseIdCourse;
     private int groupIdGroup;
     private int staffIdStaff;

    public CourseHasGroupId() {
    }

    public CourseHasGroupId(int courseIdCourse, int groupIdGroup, int staffIdStaff) {
       this.courseIdCourse = courseIdCourse;
       this.groupIdGroup = groupIdGroup;
       this.staffIdStaff = staffIdStaff;
    }
   
    public int getCourseIdCourse() {
        return this.courseIdCourse;
    }
    
    public void setCourseIdCourse(int courseIdCourse) {
        this.courseIdCourse = courseIdCourse;
    }
    public int getGroupIdGroup() {
        return this.groupIdGroup;
    }
    
    public void setGroupIdGroup(int groupIdGroup) {
        this.groupIdGroup = groupIdGroup;
    }
    public int getStaffIdStaff() {
        return this.staffIdStaff;
    }
    
    public void setStaffIdStaff(int staffIdStaff) {
        this.staffIdStaff = staffIdStaff;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CourseHasGroupId) ) return false;
		 CourseHasGroupId castOther = ( CourseHasGroupId ) other; 
         
		 return (this.getCourseIdCourse()==castOther.getCourseIdCourse())
 && (this.getGroupIdGroup()==castOther.getGroupIdGroup())
 && (this.getStaffIdStaff()==castOther.getStaffIdStaff());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCourseIdCourse();
         result = 37 * result + this.getGroupIdGroup();
         result = 37 * result + this.getStaffIdStaff();
         return result;
   }   


}


