package Pojo;
// Generated Mar 22, 2015 11:30:04 AM by Hibernate Tools 3.6.0



/**
 * GroupsCourses generated by hbm2java
 */
public class GroupsCourses  implements java.io.Serializable {


     private Integer groupId;
     private Group group;

    public GroupsCourses() {
    }

    public GroupsCourses(Group group) {
       this.group = group;
    }
   
    public Integer getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }
    public Group getGroup() {
        return this.group;
    }
    
    public void setGroup(Group group) {
        this.group = group;
    }




}


