package Pojo;
// Generated Mar 22, 2015 11:30:04 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Lab generated by hbm2java
 */
public class Lab  implements java.io.Serializable {


     private Integer idLab;
     private Course course;
     private String name;
     private String description;
     private Date startDate;
     private Date endDate;
     private UsersAssistance usersAssistance;
     private Set usersDeliveries = new HashSet(0);

    public Lab() {
    }

	
    public Lab(Course course, String name, String description, Date startDate, Date endDate) {
        this.course = course;
        this.name = name;
        this.description = description;
        this.startDate = startDate;
        this.endDate = endDate;
    }
    public Lab(Course course, String name, String description, Date startDate, Date endDate, UsersAssistance usersAssistance, Set usersDeliveries) {
       this.course = course;
       this.name = name;
       this.description = description;
       this.startDate = startDate;
       this.endDate = endDate;
       this.usersAssistance = usersAssistance;
       this.usersDeliveries = usersDeliveries;
    }
   
    public Integer getIdLab() {
        return this.idLab;
    }
    
    public void setIdLab(Integer idLab) {
        this.idLab = idLab;
    }
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public UsersAssistance getUsersAssistance() {
        return this.usersAssistance;
    }
    
    public void setUsersAssistance(UsersAssistance usersAssistance) {
        this.usersAssistance = usersAssistance;
    }
    public Set getUsersDeliveries() {
        return this.usersDeliveries;
    }
    
    public void setUsersDeliveries(Set usersDeliveries) {
        this.usersDeliveries = usersDeliveries;
    }




}


