package Pojo;
// Generated Mar 22, 2015 7:46:58 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Staff generated by hbm2java
 */
public class Staff  implements java.io.Serializable {


     private Integer idStaff;
     private int isAdmin;
     private int position;
     private Set courses = new HashSet(0);

    public Staff() {
    }

	
    public Staff(int isAdmin, int position) {
        this.isAdmin = isAdmin;
        this.position = position;
    }
    public Staff(int isAdmin, int position, Set courses) {
       this.isAdmin = isAdmin;
       this.position = position;
       this.courses = courses;
    }
   
    public Integer getIdStaff() {
        return this.idStaff;
    }
    
    public void setIdStaff(Integer idStaff) {
        this.idStaff = idStaff;
    }
    public int getIsAdmin() {
        return this.isAdmin;
    }
    
    public void setIsAdmin(int isAdmin) {
        this.isAdmin = isAdmin;
    }
    public int getPosition() {
        return this.position;
    }
    
    public void setPosition(int position) {
        this.position = position;
    }
    public Set getCourses() {
        return this.courses;
    }
    
    public void setCourses(Set courses) {
        this.courses = courses;
    }




}


