package Pojo;
// Generated Mar 22, 2015 7:46:58 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Trainee generated by hbm2java
 */
public class Trainee  implements java.io.Serializable {


     private Integer idTrainee;
     private int intake;
     private Set usersDeliveryHasTrainees = new HashSet(0);
     private Set usersAssistanceHasTrainees = new HashSet(0);
     private Set groups = new HashSet(0);
     private Set uploadFilePerLabs = new HashSet(0);

    public Trainee() {
    }

	
    public Trainee(int intake) {
        this.intake = intake;
    }
    public Trainee(int intake, Set usersDeliveryHasTrainees, Set usersAssistanceHasTrainees, Set groups, Set uploadFilePerLabs) {
       this.intake = intake;
       this.usersDeliveryHasTrainees = usersDeliveryHasTrainees;
       this.usersAssistanceHasTrainees = usersAssistanceHasTrainees;
       this.groups = groups;
       this.uploadFilePerLabs = uploadFilePerLabs;
    }
   
    public Integer getIdTrainee() {
        return this.idTrainee;
    }
    
    public void setIdTrainee(Integer idTrainee) {
        this.idTrainee = idTrainee;
    }
    public int getIntake() {
        return this.intake;
    }
    
    public void setIntake(int intake) {
        this.intake = intake;
    }
    public Set getUsersDeliveryHasTrainees() {
        return this.usersDeliveryHasTrainees;
    }
    
    public void setUsersDeliveryHasTrainees(Set usersDeliveryHasTrainees) {
        this.usersDeliveryHasTrainees = usersDeliveryHasTrainees;
    }
    public Set getUsersAssistanceHasTrainees() {
        return this.usersAssistanceHasTrainees;
    }
    
    public void setUsersAssistanceHasTrainees(Set usersAssistanceHasTrainees) {
        this.usersAssistanceHasTrainees = usersAssistanceHasTrainees;
    }
    public Set getGroups() {
        return this.groups;
    }
    
    public void setGroups(Set groups) {
        this.groups = groups;
    }
    public Set getUploadFilePerLabs() {
        return this.uploadFilePerLabs;
    }
    
    public void setUploadFilePerLabs(Set uploadFilePerLabs) {
        this.uploadFilePerLabs = uploadFilePerLabs;
    }




}


