package Pojo;
// Generated Mar 22, 2015 7:46:58 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * UploadFilePerLab generated by hbm2java
 */
public class UploadFilePerLab  implements java.io.Serializable {


     private UploadFilePerLabId id;
     private Lab lab;
     private Trainee trainee;
     private byte[] file;
     private Date uploadFileDate;

    public UploadFilePerLab() {
    }

    public UploadFilePerLab(UploadFilePerLabId id, Lab lab, Trainee trainee, byte[] file, Date uploadFileDate) {
       this.id = id;
       this.lab = lab;
       this.trainee = trainee;
       this.file = file;
       this.uploadFileDate = uploadFileDate;
    }
   
    public UploadFilePerLabId getId() {
        return this.id;
    }
    
    public void setId(UploadFilePerLabId id) {
        this.id = id;
    }
    public Lab getLab() {
        return this.lab;
    }
    
    public void setLab(Lab lab) {
        this.lab = lab;
    }
    public Trainee getTrainee() {
        return this.trainee;
    }
    
    public void setTrainee(Trainee trainee) {
        this.trainee = trainee;
    }
    public byte[] getFile() {
        return this.file;
    }
    
    public void setFile(byte[] file) {
        this.file = file;
    }
    public Date getUploadFileDate() {
        return this.uploadFileDate;
    }
    
    public void setUploadFileDate(Date uploadFileDate) {
        this.uploadFileDate = uploadFileDate;
    }




}


