package Pojo;
// Generated Mar 22, 2015 7:46:58 PM by Hibernate Tools 3.6.0



/**
 * UploadFilePerLabId generated by hbm2java
 */
public class UploadFilePerLabId  implements java.io.Serializable {


     private int traineeIdTrainee;
     private int labIdLab;

    public UploadFilePerLabId() {
    }

    public UploadFilePerLabId(int traineeIdTrainee, int labIdLab) {
       this.traineeIdTrainee = traineeIdTrainee;
       this.labIdLab = labIdLab;
    }
   
    public int getTraineeIdTrainee() {
        return this.traineeIdTrainee;
    }
    
    public void setTraineeIdTrainee(int traineeIdTrainee) {
        this.traineeIdTrainee = traineeIdTrainee;
    }
    public int getLabIdLab() {
        return this.labIdLab;
    }
    
    public void setLabIdLab(int labIdLab) {
        this.labIdLab = labIdLab;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UploadFilePerLabId) ) return false;
		 UploadFilePerLabId castOther = ( UploadFilePerLabId ) other; 
         
		 return (this.getTraineeIdTrainee()==castOther.getTraineeIdTrainee())
 && (this.getLabIdLab()==castOther.getLabIdLab());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getTraineeIdTrainee();
         result = 37 * result + this.getLabIdLab();
         return result;
   }   


}


