package Pojo;
// Generated Mar 22, 2015 11:30:04 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * UsersAssistance generated by hbm2java
 */
public class UsersAssistance  implements java.io.Serializable {


     private int labId;
     private Lab lab;
     private Set trainees = new HashSet(0);

    public UsersAssistance() {
    }

	
    public UsersAssistance(Lab lab) {
        this.lab = lab;
    }
    public UsersAssistance(Lab lab, Set trainees) {
       this.lab = lab;
       this.trainees = trainees;
    }
   
    public int getLabId() {
        return this.labId;
    }
    
    public void setLabId(int labId) {
        this.labId = labId;
    }
    public Lab getLab() {
        return this.lab;
    }
    
    public void setLab(Lab lab) {
        this.lab = lab;
    }
    public Set getTrainees() {
        return this.trainees;
    }
    
    public void setTrainees(Set trainees) {
        this.trainees = trainees;
    }




}


