package Pojo;
// Generated Mar 22, 2015 7:46:58 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * UsersAssistance generated by hbm2java
 */
public class UsersAssistance  implements java.io.Serializable {


     private int assisqueueId;
     private Set labs = new HashSet(0);
     private Set usersAssistanceHasTrainees = new HashSet(0);

    public UsersAssistance() {
    }

	
    public UsersAssistance(int assisqueueId) {
        this.assisqueueId = assisqueueId;
    }
    public UsersAssistance(int assisqueueId, Set labs, Set usersAssistanceHasTrainees) {
       this.assisqueueId = assisqueueId;
       this.labs = labs;
       this.usersAssistanceHasTrainees = usersAssistanceHasTrainees;
    }
   
    public int getAssisqueueId() {
        return this.assisqueueId;
    }
    
    public void setAssisqueueId(int assisqueueId) {
        this.assisqueueId = assisqueueId;
    }
    public Set getLabs() {
        return this.labs;
    }
    
    public void setLabs(Set labs) {
        this.labs = labs;
    }
    public Set getUsersAssistanceHasTrainees() {
        return this.usersAssistanceHasTrainees;
    }
    
    public void setUsersAssistanceHasTrainees(Set usersAssistanceHasTrainees) {
        this.usersAssistanceHasTrainees = usersAssistanceHasTrainees;
    }




}


