package Pojo;
// Generated Mar 22, 2015 7:46:58 PM by Hibernate Tools 3.6.0



/**
 * UsersDeliveryHasTrainee generated by hbm2java
 */
public class UsersDeliveryHasTrainee  implements java.io.Serializable {


     private UsersDeliveryHasTraineeId id;
     private UsersDelivery usersDelivery;
     private Trainee trainee;
     private Integer timesOfServed;
     private int served;
     private String comment;

    public UsersDeliveryHasTrainee() {
    }

	
    public UsersDeliveryHasTrainee(UsersDeliveryHasTraineeId id, UsersDelivery usersDelivery, Trainee trainee, int served) {
        this.id = id;
        this.usersDelivery = usersDelivery;
        this.trainee = trainee;
        this.served = served;
    }
    public UsersDeliveryHasTrainee(UsersDeliveryHasTraineeId id, UsersDelivery usersDelivery, Trainee trainee, Integer timesOfServed, int served, String comment) {
       this.id = id;
       this.usersDelivery = usersDelivery;
       this.trainee = trainee;
       this.timesOfServed = timesOfServed;
       this.served = served;
       this.comment = comment;
    }
   
    public UsersDeliveryHasTraineeId getId() {
        return this.id;
    }
    
    public void setId(UsersDeliveryHasTraineeId id) {
        this.id = id;
    }
    public UsersDelivery getUsersDelivery() {
        return this.usersDelivery;
    }
    
    public void setUsersDelivery(UsersDelivery usersDelivery) {
        this.usersDelivery = usersDelivery;
    }
    public Trainee getTrainee() {
        return this.trainee;
    }
    
    public void setTrainee(Trainee trainee) {
        this.trainee = trainee;
    }
    public Integer getTimesOfServed() {
        return this.timesOfServed;
    }
    
    public void setTimesOfServed(Integer timesOfServed) {
        this.timesOfServed = timesOfServed;
    }
    public int getServed() {
        return this.served;
    }
    
    public void setServed(int served) {
        this.served = served;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }




}


