package Pojo;
// Generated Mar 22, 2015 7:46:58 PM by Hibernate Tools 3.6.0



/**
 * UserPhones generated by hbm2java
 */
public class UserPhones  implements java.io.Serializable {


     private Integer userId;
     private User user;
     private String phone;

    public UserPhones() {
    }

    public UserPhones(User user, String phone) {
       this.user = user;
       this.phone = phone;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }




}


