package Pojo;
// Generated Mar 22, 2015 7:46:58 PM by Hibernate Tools 3.6.0



/**
 * UsersDeliveryHasTraineeId generated by hbm2java
 */
public class UsersDeliveryHasTraineeId  implements java.io.Serializable {


     private int usersDeliveryDelilverQueueId;
     private int traineeIdTrainee;

    public UsersDeliveryHasTraineeId() {
    }

    public UsersDeliveryHasTraineeId(int usersDeliveryDelilverQueueId, int traineeIdTrainee) {
       this.usersDeliveryDelilverQueueId = usersDeliveryDelilverQueueId;
       this.traineeIdTrainee = traineeIdTrainee;
    }
   
    public int getUsersDeliveryDelilverQueueId() {
        return this.usersDeliveryDelilverQueueId;
    }
    
    public void setUsersDeliveryDelilverQueueId(int usersDeliveryDelilverQueueId) {
        this.usersDeliveryDelilverQueueId = usersDeliveryDelilverQueueId;
    }
    public int getTraineeIdTrainee() {
        return this.traineeIdTrainee;
    }
    
    public void setTraineeIdTrainee(int traineeIdTrainee) {
        this.traineeIdTrainee = traineeIdTrainee;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsersDeliveryHasTraineeId) ) return false;
		 UsersDeliveryHasTraineeId castOther = ( UsersDeliveryHasTraineeId ) other; 
         
		 return (this.getUsersDeliveryDelilverQueueId()==castOther.getUsersDeliveryDelilverQueueId())
 && (this.getTraineeIdTrainee()==castOther.getTraineeIdTrainee());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUsersDeliveryDelilverQueueId();
         result = 37 * result + this.getTraineeIdTrainee();
         return result;
   }   


}


