package Pojo;
// Generated Mar 22, 2015 7:46:58 PM by Hibernate Tools 3.6.0



/**
 * UsersAssistanceHasTraineeId generated by hbm2java
 */
public class UsersAssistanceHasTraineeId  implements java.io.Serializable {


     private int traineeIdTrainee;
     private int usersAssistanceAssisqueueId;

    public UsersAssistanceHasTraineeId() {
    }

    public UsersAssistanceHasTraineeId(int traineeIdTrainee, int usersAssistanceAssisqueueId) {
       this.traineeIdTrainee = traineeIdTrainee;
       this.usersAssistanceAssisqueueId = usersAssistanceAssisqueueId;
    }
   
    public int getTraineeIdTrainee() {
        return this.traineeIdTrainee;
    }
    
    public void setTraineeIdTrainee(int traineeIdTrainee) {
        this.traineeIdTrainee = traineeIdTrainee;
    }
    public int getUsersAssistanceAssisqueueId() {
        return this.usersAssistanceAssisqueueId;
    }
    
    public void setUsersAssistanceAssisqueueId(int usersAssistanceAssisqueueId) {
        this.usersAssistanceAssisqueueId = usersAssistanceAssisqueueId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsersAssistanceHasTraineeId) ) return false;
		 UsersAssistanceHasTraineeId castOther = ( UsersAssistanceHasTraineeId ) other; 
         
		 return (this.getTraineeIdTrainee()==castOther.getTraineeIdTrainee())
 && (this.getUsersAssistanceAssisqueueId()==castOther.getUsersAssistanceAssisqueueId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getTraineeIdTrainee();
         result = 37 * result + this.getUsersAssistanceAssisqueueId();
         return result;
   }   


}


