package pojo;
// Generated Mar 21, 2015 12:47:58 PM by Hibernate Tools 4.3.1



/**
 * CourseHasGroup generated by hbm2java
 */
public class CourseHasGroup  implements java.io.Serializable {


     private CourseHasGroupId id;
     private Course course;
     private Group group;
     private Staff staff;

    public CourseHasGroup() {
    }

    public CourseHasGroup(CourseHasGroupId id, Course course, Group group, Staff staff) {
       this.id = id;
       this.course = course;
       this.group = group;
       this.staff = staff;
    }
   
    public CourseHasGroupId getId() {
        return this.id;
    }
    
    public void setId(CourseHasGroupId id) {
        this.id = id;
    }
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }
    public Group getGroup() {
        return this.group;
    }
    
    public void setGroup(Group group) {
        this.group = group;
    }
    public Staff getStaff() {
        return this.staff;
    }
    
    public void setStaff(Staff staff) {
        this.staff = staff;
    }




}


