package pojo;
// Generated Mar 21, 2015 12:47:58 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Group generated by hbm2java
 */
public class Group  implements java.io.Serializable {


     private Integer idGroup;
     private String name;
     private String description;
     private int isActive;
     private Set courseHasGroups = new HashSet(0);
     private Set users = new HashSet(0);
     private Set trainees = new HashSet(0);
     private GroupsCourses groupsCourses;

    public Group() {
    }

	
    public Group(String name, String description, int isActive) {
        this.name = name;
        this.description = description;
        this.isActive = isActive;
    }
    public Group(String name, String description, int isActive, Set courseHasGroups, Set users, Set trainees, GroupsCourses groupsCourses) {
       this.name = name;
       this.description = description;
       this.isActive = isActive;
       this.courseHasGroups = courseHasGroups;
       this.users = users;
       this.trainees = trainees;
       this.groupsCourses = groupsCourses;
    }
   
    public Integer getIdGroup() {
        return this.idGroup;
    }
    
    public void setIdGroup(Integer idGroup) {
        this.idGroup = idGroup;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public int getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(int isActive) {
        this.isActive = isActive;
    }
    public Set getCourseHasGroups() {
        return this.courseHasGroups;
    }
    
    public void setCourseHasGroups(Set courseHasGroups) {
        this.courseHasGroups = courseHasGroups;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }
    public Set getTrainees() {
        return this.trainees;
    }
    
    public void setTrainees(Set trainees) {
        this.trainees = trainees;
    }
    public GroupsCourses getGroupsCourses() {
        return this.groupsCourses;
    }
    
    public void setGroupsCourses(GroupsCourses groupsCourses) {
        this.groupsCourses = groupsCourses;
    }




}


