package pojo;
// Generated Mar 21, 2015 12:47:58 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Notifications generated by hbm2java
 */
public class Notifications  implements java.io.Serializable {


     private int notificationId;
     private String message;
     private Set users = new HashSet(0);

    public Notifications() {
    }

	
    public Notifications(int notificationId, String message) {
        this.notificationId = notificationId;
        this.message = message;
    }
    public Notifications(int notificationId, String message, Set users) {
       this.notificationId = notificationId;
       this.message = message;
       this.users = users;
    }
   
    public int getNotificationId() {
        return this.notificationId;
    }
    
    public void setNotificationId(int notificationId) {
        this.notificationId = notificationId;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


