package pojo;
// Generated Mar 21, 2015 12:47:58 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Staff generated by hbm2java
 */
public class Staff  implements java.io.Serializable {


     private Integer idStaff;
     private User user;
     private int isAdmin;
     private int position;
     private Set courseHasGroups = new HashSet(0);

    public Staff() {
    }

	
    public Staff(User user, int isAdmin, int position) {
        this.user = user;
        this.isAdmin = isAdmin;
        this.position = position;
    }
    public Staff(User user, int isAdmin, int position, Set courseHasGroups) {
       this.user = user;
       this.isAdmin = isAdmin;
       this.position = position;
       this.courseHasGroups = courseHasGroups;
    }
   
    public Integer getIdStaff() {
        return this.idStaff;
    }
    
    public void setIdStaff(Integer idStaff) {
        this.idStaff = idStaff;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public int getIsAdmin() {
        return this.isAdmin;
    }
    
    public void setIsAdmin(int isAdmin) {
        this.isAdmin = isAdmin;
    }
    public int getPosition() {
        return this.position;
    }
    
    public void setPosition(int position) {
        this.position = position;
    }
    public Set getCourseHasGroups() {
        return this.courseHasGroups;
    }
    
    public void setCourseHasGroups(Set courseHasGroups) {
        this.courseHasGroups = courseHasGroups;
    }




}


