package pojo;
// Generated Mar 21, 2015 12:47:58 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UsersDelivery generated by hbm2java
 */
public class UsersDelivery  implements java.io.Serializable {


     private int delilverQueueId;
     private Lab lab;
     private Date toWhenDate;
     private int served;
     private Set trainees = new HashSet(0);

    public UsersDelivery() {
    }

	
    public UsersDelivery(int delilverQueueId, Lab lab, int served) {
        this.delilverQueueId = delilverQueueId;
        this.lab = lab;
        this.served = served;
    }
    public UsersDelivery(int delilverQueueId, Lab lab, Date toWhenDate, int served, Set trainees) {
       this.delilverQueueId = delilverQueueId;
       this.lab = lab;
       this.toWhenDate = toWhenDate;
       this.served = served;
       this.trainees = trainees;
    }
   
    public int getDelilverQueueId() {
        return this.delilverQueueId;
    }
    
    public void setDelilverQueueId(int delilverQueueId) {
        this.delilverQueueId = delilverQueueId;
    }
    public Lab getLab() {
        return this.lab;
    }
    
    public void setLab(Lab lab) {
        this.lab = lab;
    }
    public Date getToWhenDate() {
        return this.toWhenDate;
    }
    
    public void setToWhenDate(Date toWhenDate) {
        this.toWhenDate = toWhenDate;
    }
    public int getServed() {
        return this.served;
    }
    
    public void setServed(int served) {
        this.served = served;
    }
    public Set getTrainees() {
        return this.trainees;
    }
    
    public void setTrainees(Set trainees) {
        this.trainees = trainees;
    }




}


